Update keras.ipynb
AttributeError                            Traceback (most recent call last)
<ipython-input-29-24ca6489a6ec> in <module>()
      4 
      5 # Configure a model for categorical classification.
----> 6 model.compile(optimizer=tf.train.RMSPropOptimizer(0.01),
      7               loss=tf.keras.losses.categorical_crossentropy,
      8               metrics=[tf.keras.metrics.categorical_accuracy])

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'RMSPropOptimizer'

changed from
tf.train.RMSPropOptimizer
to
tf.keras.optimizers.RMSprop