Update keras.ipynb
AttributeError                            Traceback (most recent call last)
<ipython-input-21-1a9adc696f74> in <module>()
      7 layers.Dense(10, activation='softmax')])
      8 
----> 9 model.compile(optimizer=tf.train.AdamOptimizer(0.001),
     10               loss='categorical_crossentropy',
     11               metrics=['accuracy'])

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'

changed from
tf.train.AdamOptimizer
to 
tf.optimizers.Adam