Update keras.ipynb
AttributeError                            Traceback (most recent call last)
<ipython-input-64-82299408ab8f> in <module>()
      3 model.add(layers.Dense(1, activation='sigmoid'))
      4 
----> 5 optimizer = tf.train.GradientDescentOptimizer(0.2)
      6 
      7 model.compile(loss='binary_crossentropy', optimizer=optimizer)

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'GradientDescentOptimizer'

changed from
tf.train.GradientDescentOptimizer
to
tf.optimizers.SGD