Update keras.ipynb
AttributeError                            Traceback (most recent call last)
<ipython-input-5-1c351d950b73> in <module>()
      4 from tensorflow.keras import layers
      5 
----> 6 print(tf.VERSION)
      7 print(tf.keras.__version__)

AttributeError: module 'tensorflow' has no attribute 'VERSION'

changed from
print(tf.VERSION)
to 
print(tf.__version__)